Repository eveseat/eveapi, pull requests merged in 2018-12, with the labels that each got.

#131 Outdated endpoints
  src/Jobs/Character/Notifications.php
  src/Jobs/Market/Corporation/Orders.php
  src/database/migrations/2018_11_27_214358_update_corporation_orders_to_v3.php
Labels: ESI

#129 459 character killmail
  src/Models/Killmails/CharacterKillmail.php
  src/Models/Killmails/KillmailDetail.php
  src/Models/Killmails/KillmailVictim.php
Labels: enhancement

#132 Character wallet transactions
  src/Models/Wallet/CharacterWalletTransaction.php
Labels: enhancement

#133 Updated character mail datatables
  src/Models/Mail/MailHeader.php
Labels: enhancement

#134 Observer mining data needs last_updated as a primary key
  src/Jobs/Industry/Corporation/Mining/ObserverDetails.php
  src/Models/Industry/CorporationIndustryMiningObserverData.php
  src/database/migrations/2018_12_09_110558_fix_corporation_industry_mining_observer_data_primary_keys.php
Labels: bug
