Repository eveseat/eveapi, pull requests merged in 2019-05, with the labels that each got.

#155 Add characters and alliance to Corporation model
  src/Models/Corporation/CorporationInfo.php
Labels: enhancement

#156 feat(esi): bump ESI endpoint promoted on May 2019
  src/Jobs/Wallet/Character/Journal.php
Labels: ESI

#157 fix(config): put environment variables into config file
  src/Config/eveapi.config.php
  src/Helpers/EseyeSetup.php
Labels: fix

#158 fix(relationship): fix a reference error
  src/Models/Corporation/CorporationInfo.php
Labels: fix
