Repository eveseat/eveapi, pull requests merged in 2020-02, with the labels that each got.

#186 refactor(notifications): parse text field
  src/Models/Character/CharacterNotification.php
Labels: enhancement

#189 fix(jobs): ensure distinct skill level are preserved while updating queue
  src/Jobs/Skills/Character/Queue.php
Labels: fix

#190 fix: ensure enqueued skills are stored
  src/Jobs/Skills/Character/Queue.php
  src/database/migrations/2020_02_09_182013_add_queues_position_to_skill_queue_table_pk.php
Labels: fix

#191 fix: ensure enqueued skills are stored
  src/Jobs/Skills/Character/Queue.php
  src/database/migrations/2020_02_09_182013_add_queues_position_to_skill_queue_table_pk.php
Labels: fix

#192 feat(assets): bump endpoints to v4 according to ESI changes
  src/Jobs/Assets/Character/Assets.php
  src/Jobs/Assets/Corporation/Assets.php
  src/database/migrations/2020_02_09_192020_update_character_assets_v4.php
  src/database/migrations/2020_02_09_192020_update_corporation_assets_v4.php
Labels: ESI

#193 feat(assets): bump endpoints to v4 according to ESI changes
  src/Jobs/Assets/Character/Assets.php
  src/Jobs/Assets/Corporation/Assets.php
  src/database/migrations/2020_02_09_192020_update_character_assets_v4.php
  src/database/migrations/2020_02_09_192020_update_corporation_assets_v4.php
Labels: ESI

#194 feat(jobs): store updated refresh token returned by SSO when refreshing access tokens
  src/Jobs/EsiBase.php
Labels: enhancement

#197 Update CorporationMemberTracking model from User to RefreshToken
  src/Models/Corporation/CorporationMemberTracking.php
Labels: enhancement
